reusable workflow to deploy Next.js to Pages
qibogang/qibogang.github.io pull request #30
Opened 2022-12-06 12:29 UTC by Edoardo-Pedicillo

In this PR, I have changed the `publish.yml` workflow in order to implement the reusable workflow `publish-next-on-ghpages.yml`.

2022-12-12 18:29 UTC, AleCandido requested changes
I forgot to submit this review some time ago

2022-12-12 18:29 UTC, AleCandido commented
Apart from the very minor point above, is there anything else blocking this?

2022-12-14 10:26 UTC, AleCandido commented
> Apart from the very minor point above, is there anything else blocking this?

@Edoardo-Pedicillo @MatteoRobbiati

2022-12-14 10:40 UTC, MatteoRobbiati commented
> Apart from the very minor point above, is there anything else blocking this?

I think it can be merged.

2022-12-14 10:42 UTC, AleCandido commented on .github/workflows/publish.yml
> +  deploy-docs:
```suggestion
  publish:
```

2022-12-14 10:43 UTC, AleCandido approved these changes

2022-12-14 10:43 UTC, merged