Latest & stable docs
qibogang/qibogang.github.io pull request #55
Opened 2022-12-12 10:57 UTC by MatteoRobbiati

In this PR the links to the docs are updated: now we have `latest` and `stable` versions for `qibo` documentation, thanks to the new workflows provided by @Edoardo-Pedicillo.

I have decided to set as default link the one to the `stable` version. It is a choice and I am not sure that's the best one. Please let me know if you agree.

The same must be done for `qibolab` and `qibocal`.

2022-12-12 18:12 UTC, AleCandido commented
> I have decided to set as default link the one to the `stable` version. It is a choice and I am not sure that's the best one. Please let me know if you agree.

I agree with your choice, I have seen both `latest` (i.e. `master`) and `stable` (last tag) used as defaults in various docs. Essentially they are both fine by me, but usually `stable` is more useful, since people tend to use versions on PyPI rather than directly from source (or git URL, that is the same).

2022-12-12 18:16 UTC, AleCandido requested changes

2022-12-13 12:48 UTC, MatteoRobbiati commented on pages/docs/qibo/stable.js
> +}
Thank you. I have opened ad issue for this.

2022-12-13 13:27 UTC, andrea-pasquale approved these changes

2022-12-14 08:13 UTC, merged